# Generated by Django 3.1.2 on 2020-11-13 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20201112_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dateFrom',
            new_name='date_From',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dateTo',
            new_name='date_To',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='date_availabl',
            new_name='date_available',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='anyDayAnyHour',
            new_name='got_transportation',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='gotTransportation',
            new_name='graduated_Trade',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='howDidYouHearAboutPosition',
            new_name='how_Did_You_Hear_About_Position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='graduatedTrade',
            new_name='is_manager',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='jobTitle',
            new_name='job_Title',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='last_collegeYear_completed',
            new_name='last_college_Year_completed',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='nameOfEmployer',
            new_name='name_Of_Employer',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='willingToTravel',
            new_name='willing_to_travel',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='workHoliday',
            new_name='work_any_Day_Any_Hour',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='pay_rate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='start_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='work_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disclaimer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='friday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='friday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='monday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saturday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='saturday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sunday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sunday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thursday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thursday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tuesday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tuesday_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wenesday_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='wenesday_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
