# Generated by Django 3.1.2 on 2020-11-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20201110_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
